### ISSUE TITLE
How can I get index of the current card? Can I jump on the specific card index?

### ISSUE THREAD

**Issue by Suyashk44** [chitezh/react-native-swiper-animated#11]
Thanks for the great module. I want to know when I reach at the end of array. Is there some way I can detect swipeLeft and swipeRight events? I could track the index using those.

**Comment by chitezh** [comment]
@Suyashk44 Yeah. I just realized that there is no `getCurrentIndex`. There is only `getCurrentCard`.

However, you can track the end of an array by listening on the `onFinish` prop. 
You can also get left or right using `onRightSwipe` and `onLeftSwipe`. I think you can actually use it to get the current index

**Comment by Suyashk44** [comment]
Thank you very much!! That works.

**Comment by NainalChauhan** [comment]
In my case  `onFinish` get called when view is creating and it doesn't call when swipe ends.

```
         <Swiper
                    style={styles.wrapper}
                    showPagination={false}
                    smoothTransition={true}
                    // stack={true}
                    swipeDirection='left'
                    // loop={true}
                    dragDownToBack
                    dragY
                    swipeThroughStack={true}
                    onFinish={this.onSwipeFinisih()}
                    >
```
