### ISSUE TITLE
Change direction

### ISSUE THREAD

**Issue by choo737** [chitezh/react-native-swiper-animated#15]
Is it possible for me to change the swipe direction? 
Currently when I swipe to the right it moves to next page, I need to go to next page by swiping to the left.

**Comment by chitezh** [comment]
no, it's not possible presently but you can fork it and alternate the booleans in lines 
https://github.com/chitezh/react-native-swiper-animated/blob/master/src/Swiper.js#L279 and https://github.com/chitezh/react-native-swiper-animated/blob/master/src/Swiper.js#L282

Or even better, use a prop to control that

**Comment by choo737** [comment]
Thanks you for getting back to me so quickly~ forked it and done it.. Thanks!

**Comment by chitezh** [comment]
closing...
