### ISSUE TITLE
Need to show back side cards in the right side

### ISSUE THREAD

**Issue by swaroopa94** [chitezh/react-native-swiper-animated#17]
Hi 
I am using your module and now I am getting the design like this : 

![simulator screen shot - iphone 6 - 2018-01-05 at 19 17 44](https://user-images.githubusercontent.com/19324363/34611830-2013d7da-f24d-11e7-86af-de2de7b847e7.png)

But the back cards are displaying in the bottom but I want to display them on right side 
Can you tell me how to do that ?

**Comment by chitezh** [comment]
Hey @swaroopa94 You can toggle the `stack`prop to `false`

**Comment by swaroopa94** [comment]
But If I do stack to false does the stack appears on the right side ???

**Comment by chitezh** [comment]
Could you make a sketch of what you’re trying to achieve?

**Comment by swaroopa94** [comment]
@chitezh yes I will snd you a screenshot 
![screen shot 2018-01-08 at 11 47 37 am](https://user-images.githubusercontent.com/19324363/34660618-c1b1469a-f469-11e7-866f-9e5f2093b345.png)

If you see on  the right side there we can see the back cards
I just want like this

**Comment by swaroopa94** [comment]
@chitezh  Hi Can you please respond faster as its urgent 
And other thing is if  swipe left then the card should go to back side like below screenshot
![screen shot 2018-01-09 at 11 39 54 am](https://user-images.githubusercontent.com/19324363/34707161-f564739a-f531-11e7-827f-f481e33de4c0.png)

**Comment by chitezh** [comment]
Hey @swaroopa94 

Sorry for the late response. 
You will have to fork the repo and make some changes to get the behavior you desire.

1. see https://github.com/chitezh/react-native-swiper-animated/issues/15#issuecomment-345031387 about changing direction

2. about the effect you desire, alternate scaleY and scaleX in https://github.com/chitezh/react-native-swiper-animated/blob/master/src/Swiper.js#L519-L628

**Comment by swaroopa94** [comment]
@chitezh 
Hi Thanks for the response 
I will try that and inform u soon....
