### ISSUE TITLE
Loop in Stack mode

### ISSUE THREAD

**Issue by gabrielmicko** [chitezh/react-native-swiper-animated#18]
Is it possible?

**Comment by chitezh** [comment]
Unfortunately, it's not

**Comment by gabrielmicko** [comment]
Thanks!

**Comment by mstraz** [comment]
Hi @chitezh 

First of all, I appreciate this awesome tinder-like swiper.
As in my research, this is the most smooth tinder-like swiper.
The only insufficiency is that it doesn't support loop in stack mode.
Do you have any plan to implement loop in stack mode?

Currently it's not available to swipe last card in stack mode.
1. It would be great if we can swipe last card and after swiping all cards, refresh card stack to the initial state.
2. Further more, it would be great if we can completely loop cards visually as well: the card swiped should be added to the end of stack.
Do you have any suggestion for me to achieve one of the above behavior?
Is there any handler that I can handle the event of swiping last card? 

Thanks
Milan

**Comment by chitezh** [comment]
Thanks @mstraz 

1. I'll look at adding the looping ability to stack.
2. While looking at 1, I might be able to tell you what you need to do to get 2.

Please, remind me if there's no update on this in the next day

**Comment by gabrielmicko** [comment]
@mstraz thank you for your comment. I totally agree.

**Comment by mstraz** [comment]
Thanks @chitezh 

Could you please let me know what I need to do to get #2?

**Comment by mstraz** [comment]
Hi @chitezh 

Have you had a chance to look into this issue?
