### ISSUE TITLE
Constructors of Child components are called every time I changed page

### ISSUE THREAD

**Issue by punksta** [chitezh/react-native-swiper-animated#19]
Hey, thanks for cool library. I got problems with rendering of heavy components in stack.

I have static large array of items with static unique keys.
```
 <Swiper
        paginationLeft={""}
	paginationRight={""}
	smoothTransition
	stack
	dragDownToBack
        stackOffsetY={-7}
	stackDepth={3}
	swiper={false}
	showToolbar={false}
	showPagination={false}
	dragY={false}
  >
    {items.map(item => (
      <FooBar key={item.id}>
      </FooBar>
      ))}
</Swiper>
```
Those `FooBar` components are heavy, I have `WebView` inside. So I want them to update, not create on each page changing.

I believe that reason is static keys here:
https://github.com/chitezh/react-native-swiper-animated/blob/d11913c8331c1a267c95755f77ec23eaa3a6a165/src/Swiper.js#L613-L620

**Comment by chitezh** [comment]
published `1.3.1`
