### ISSUE TITLE
Can it handle a large number of views

### ISSUE THREAD

**Issue by onehassan** [chitezh/react-native-swiper-animated#2]
I wondered if it can handle a large number of cards, like in the case of a book that's 100's of pages long?

**Comment by chitezh** [comment]
Thank you @HsanBenJobrane,

I haven't tried pages that long. 
I do believe it would handle them just fine

Kingsley

**Comment by chitezh** [comment]
This will require a refactor to work optimally. Moving to VirtualizedList or FlatList instead of rendering all pages at one
