### ISSUE TITLE
Invariant Violation error

### ISSUE THREAD

**Issue by smaharj1** [chitezh/react-native-swiper-animated#25]
Hi,

I am getting Invariant Violation error. "Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

I tried it with 1.3.1 and 1.4.0 versions. But still, I am facing the same issue. 

In my component, I am running Swiper as
```
<Swiper stack loop showPagination={false} style={{padding:10}}> 
<View style={styles.slide1}>
    <Text style={styles.text}>Hello Swiper</Text>
  </View>
  <View style={styles.slide2}>
    <Text style={styles.text}>Beautiful</Text>
  </View>
</Swiper>
```
It is just like shown in the example. 

<img width="372" alt="screen shot 2018-08-12 at 10 40 28 pm" src="https://user-images.githubusercontent.com/8810802/44010576-4a4a1c36-9e81-11e8-98cf-1735c9800a37.png">

**Comment by Retiznyk** [comment]
It seems that `react-native-material-ui` has breaking changes in 1.30 version and there are no `ThemeProvider` anymore, so `Swiper's` render throws an error after `npm install` command

**Comment by chitezh** [comment]
Thanks for the info.
Making to fixes for this.

1. a patch to the current version which locks the `react-native-material-ui` version to 1.22.0 (before Theme rewrite)
2. a minor/major release which removes react-native-material-ui
