### ISSUE TITLE
where is the leaf style ?

### ISSUE THREAD

**Issue by geminiyellow** [chitezh/react-native-swiper-animated#29]
hi @chitezh , thanks for your great work.
is there styles for the [leaf.gif](https://github.com/chitezh/react-native-swiper-animated/blob/master/examples/shots/leaf.gif) ?

**Comment by chitezh** [comment]
leaf.gif is a shot from a past project. I may not be able to share the code with you but I could guide you through specific parts. Holla @ ochu.kc@gmail.com

**Comment by geminiyellow** [comment]
thank you sir, i send a mail to your gmail. best regards.
