### ISSUE TITLE
jumpToIndex animation / inverted animations

### ISSUE THREAD

**Issue by cwagner22** [chitezh/react-native-swiper-animated#4]
Thanks for the great lib.
I've forked it to add support to animations when using `jumpToIndex`.
However I'm not making a PR because I've inverted the swiping directions. I think it makes more sense to swipe left to load the next cards and the opposite. It feels more natural to me, for example it's the same when using iBooks to change pages. (related article: https://ux.stackexchange.com/questions/71910/swipe-in-which-direction-to-get-to-the-next-newest-article)
Maybe it'd be useful to add a property to inverse the animations.

Also FWI I had to run additional commands to get the examples to run:
```
npm i # root folder
# in examples
npm i buffer
npm i react-native-vector-icons
```

**Comment by chitezh** [comment]
Thanks, @cwagner22 The topic is really debatable. What might be good is to add `prop` that can be used to toggle the direction.

>Also FWI I had to run additional commands to get the examples to run

Thanks again, I'll update the readme
