### ISSUE TITLE
How to use forceRightSwipe ?

### ISSUE THREAD

**Issue by eddie51405** [chitezh/react-native-swiper-animated#7]
Hello, I add a button in the view. When I click the button, I want to swipe right automatically. However, I don't know how to use the method forceRightSwipe. Cold you please give me a help?

**Comment by chitezh** [comment]
An example can be found here https://github.com/chitezh/react-native-swiper-animated/blob/master/examples/components/Extended/index.js#L59-L76

**Comment by eddie51405** [comment]
Thanks. Your are so nice!
