### ISSUE TITLE
swipe on android

### ISSUE THREAD

**Issue by neo125874** [chitezh/react-native-swiper-animated#8]
i use this on android not working, any idea about that? thanks

**Comment by chitezh** [comment]
Thanks, @neo125874. What error are you getting?

**Comment by neo125874** [comment]
@chitezh  there's no error, just can't swipe, code below:

`<Swiper
          style={{backgroundColor: 'transparent'}}
          paginationStyle={{ container: { backgroundColor: 'transparent' } }}
          paginationLeft={''}
          paginationRight={''}
          smoothTransition
          loop
          showPagination={false}
          >
          {this.state.sketchHist.map(sh => {
            var src={uri: sh.val.url}
            return (
              <Image
                indicator={Progress}
                source={src}
                style={styles.image}
              />)
          })}
        </Swiper>`

**Comment by chitezh** [comment]
Can you try running the example snippet in the readme?

**Comment by neo125874** [comment]
@chitezh not working either, would it be caused by putting in the modal?

**Comment by chitezh** [comment]
I'm not sure I understand what you mean by that. But I think you should first try to get the example to show on a blank page before tweaking

**Comment by moshedri** [comment]
i have tried it in android as well and it's working fine for me , clearly not an android issue 

this issue seems like it could be close

**Comment by chitezh** [comment]
Thanks @moshedri

**Comment by harjeetxeno** [comment]
I am facing the same issue, when Swiper is put in a modal pop up window, swipe gesture is not working though it works with this.swiper.forceRightSwipe();

**Comment by chitezh** [comment]
@harjeetxeno Something is likely blocking the touch events on the modal. Maybe try playing around with `pointerEvents: none` on the containing view
